# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/aaron/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.4892.24/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/aaron/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.4892.24/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aaron/CLionProjects/seminar_assignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aaron/CLionProjects/seminar_assignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/aaron/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.4892.24/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/aaron/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.4892.24/bin/cmake/linux/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/CLionProjects/seminar_assignment/CMakeFiles /home/aaron/CLionProjects/seminar_assignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron/CLionProjects/seminar_assignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named seminar_assignment

# Build rule for target.
seminar_assignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seminar_assignment
.PHONY : seminar_assignment

# fast build rule for target.
seminar_assignment/fast:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/build
.PHONY : seminar_assignment/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/main.cpp.s
.PHONY : main.cpp.s

model/bigraph.o: model/bigraph.cpp.o

.PHONY : model/bigraph.o

# target to build an object file
model/bigraph.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/bigraph.cpp.o
.PHONY : model/bigraph.cpp.o

model/bigraph.i: model/bigraph.cpp.i

.PHONY : model/bigraph.i

# target to preprocess a source file
model/bigraph.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/bigraph.cpp.i
.PHONY : model/bigraph.cpp.i

model/bigraph.s: model/bigraph.cpp.s

.PHONY : model/bigraph.s

# target to generate assembly for a file
model/bigraph.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/bigraph.cpp.s
.PHONY : model/bigraph.cpp.s

model/graph.o: model/graph.cpp.o

.PHONY : model/graph.o

# target to build an object file
model/graph.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/graph.cpp.o
.PHONY : model/graph.cpp.o

model/graph.i: model/graph.cpp.i

.PHONY : model/graph.i

# target to preprocess a source file
model/graph.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/graph.cpp.i
.PHONY : model/graph.cpp.i

model/graph.s: model/graph.cpp.s

.PHONY : model/graph.s

# target to generate assembly for a file
model/graph.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/graph.cpp.s
.PHONY : model/graph.cpp.s

model/seminar.o: model/seminar.cpp.o

.PHONY : model/seminar.o

# target to build an object file
model/seminar.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/seminar.cpp.o
.PHONY : model/seminar.cpp.o

model/seminar.i: model/seminar.cpp.i

.PHONY : model/seminar.i

# target to preprocess a source file
model/seminar.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/seminar.cpp.i
.PHONY : model/seminar.cpp.i

model/seminar.s: model/seminar.cpp.s

.PHONY : model/seminar.s

# target to generate assembly for a file
model/seminar.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/seminar.cpp.s
.PHONY : model/seminar.cpp.s

model/student.o: model/student.cpp.o

.PHONY : model/student.o

# target to build an object file
model/student.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/student.cpp.o
.PHONY : model/student.cpp.o

model/student.i: model/student.cpp.i

.PHONY : model/student.i

# target to preprocess a source file
model/student.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/student.cpp.i
.PHONY : model/student.cpp.i

model/student.s: model/student.cpp.s

.PHONY : model/student.s

# target to generate assembly for a file
model/student.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/model/student.cpp.s
.PHONY : model/student.cpp.s

utils/Hungarian.o: utils/Hungarian.cpp.o

.PHONY : utils/Hungarian.o

# target to build an object file
utils/Hungarian.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/utils/Hungarian.cpp.o
.PHONY : utils/Hungarian.cpp.o

utils/Hungarian.i: utils/Hungarian.cpp.i

.PHONY : utils/Hungarian.i

# target to preprocess a source file
utils/Hungarian.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/utils/Hungarian.cpp.i
.PHONY : utils/Hungarian.cpp.i

utils/Hungarian.s: utils/Hungarian.cpp.s

.PHONY : utils/Hungarian.s

# target to generate assembly for a file
utils/Hungarian.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/utils/Hungarian.cpp.s
.PHONY : utils/Hungarian.cpp.s

utils/TopTradingCycle.o: utils/TopTradingCycle.cpp.o

.PHONY : utils/TopTradingCycle.o

# target to build an object file
utils/TopTradingCycle.cpp.o:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/utils/TopTradingCycle.cpp.o
.PHONY : utils/TopTradingCycle.cpp.o

utils/TopTradingCycle.i: utils/TopTradingCycle.cpp.i

.PHONY : utils/TopTradingCycle.i

# target to preprocess a source file
utils/TopTradingCycle.cpp.i:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/utils/TopTradingCycle.cpp.i
.PHONY : utils/TopTradingCycle.cpp.i

utils/TopTradingCycle.s: utils/TopTradingCycle.cpp.s

.PHONY : utils/TopTradingCycle.s

# target to generate assembly for a file
utils/TopTradingCycle.cpp.s:
	$(MAKE) -f CMakeFiles/seminar_assignment.dir/build.make CMakeFiles/seminar_assignment.dir/utils/TopTradingCycle.cpp.s
.PHONY : utils/TopTradingCycle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... seminar_assignment"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/bigraph.o"
	@echo "... model/bigraph.i"
	@echo "... model/bigraph.s"
	@echo "... model/graph.o"
	@echo "... model/graph.i"
	@echo "... model/graph.s"
	@echo "... model/seminar.o"
	@echo "... model/seminar.i"
	@echo "... model/seminar.s"
	@echo "... model/student.o"
	@echo "... model/student.i"
	@echo "... model/student.s"
	@echo "... utils/Hungarian.o"
	@echo "... utils/Hungarian.i"
	@echo "... utils/Hungarian.s"
	@echo "... utils/TopTradingCycle.o"
	@echo "... utils/TopTradingCycle.i"
	@echo "... utils/TopTradingCycle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

